name: 'pages-action'
description: 'Deploy Cloudflare Pages with GitHub Actions'
author: 'Seokmin Hong'
inputs:
  accountId:
    required: true
    description: 'Cloudflare account ID'
  projectName:
    required: true
    description: 'Name of the project'
  email:
    required: true
    description: User's email
  authKey:
    required: true
    description: API key for user
  interval:
    required: false
    description: Interval for polling (ms). Default is 3000
runs:
  using: 'node14'
  main: 'dist/index.js'
