name: 'pages-action'
description: 'Deploy Cloudflare Pages with GitHub Actions'
author: 'Seokmin Hong'
inputs:
  accountId:
    required: true
    description: 'Cloudflare account ID'
  projectName:
    required: true
    description: 'Name of the project'
  token:
    required: true
    description: 'Auth token'
  interval:
    required: false
    description: Interval for polling (ms). Default is 3000
runs:
  using: 'node16'
  main: 'dist/index.js'
